# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20170225_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Service'),
            preserve_default=False,
        ),
    ]
