# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_fooditems_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='service',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='service',
            field=models.ManyToManyField(to='apis.Service'),
        ),
    ]
